### ISSUE TITLE
npm tarball has files with timestamp 1970-01-01

### ISSUE THREAD

**Issue by josch** [hsluv/hsluv#81] opened 2021-11-01 12:03 UTC
To reproduce:

```
curl -s https://registry.npmjs.org/hsluv/-/hsluv-0.1.0.tgz | tar tvz
-rwxr-xr-x 1000/1000       462 1970-01-01 01:00 package/package.json
-rwxr-xr-x 1000/1000      2110 1970-01-01 01:00 package/README.md
-rw-r--r-- 1000/1000      9421 1970-01-01 01:00 package/hsluv.js
-rwxr-xr-x 1000/1000      1185 1970-01-01 01:00 package/hsluv.d.ts
```

Please publish a tarball containing files with a valid date.

**Comment by boronine** [comment] 2021-11-01 13:02
This timestamp comes from our build system Nix, this is 0 in [UNIX time](https://en.wikipedia.org/wiki/Unix_time). Is is causing any issues on your end?

**Comment by boronine** [comment] 2021-11-01 13:09
I just discovered that ZIP does not support timestamps < 1980, it's referenced in the Nix docs"
https://nixos.org/manual/nixpkgs/stable/#python-setup.py-bdist_wheel-cannot-create-.whl

Most likely you ran into issues when creating ZIPs? In any case this is a legitimate issue, we should at least override the timestamp with 1980-01-01.

**Comment by josch** [comment] 2021-11-01 13:09
Yes, Debian policy does not allow that timestamp. The reason is, that with a non-changing timestamp, backup systems (and also rsync) will not see a change of file contents because its timestamp didn't change and if files are served by a webserver the `Last-Modified` header would be wrong.

To work around this problem, I set the timestamp to `SOURCE_DATE_EPOCH` which during Debian package builds is set to the debian/changelog timestamp of the last entry:

https://salsa.debian.org/js-team/node-hsluv/-/blob/master/debian/rules#L10

But I see that this is a Nix issue so there is nothing you can do about it and you should probably close this bug. Thanks!

**Comment by boronine** [comment] 2021-11-01 13:21
Interesting, thanks for the info as I was not aware of this Debian policy.

It is definitely fixable on our end, but I have to research a bit for the way to approach it.

Do you have any insight on how this Debian policy is reconciled with the [Reproducible builds](https://wiki.debian.org/ReproducibleBuilds) initiative? Does Debian recommend any approach in setting these timestamps?

**Comment by josch** [comment] 2021-11-01 13:26
Yes, during package builds the `SOURCE_DATE_EPOCH` variable is set to the timestamp of the latest entry in `debian/changelog`. That way, package builds can be reproducible and that's why it doesn't conflict with reproducible builds. As you can see from the green "reprotest" job in our CI, the package is still reproducible with the change I linked to in my last message: https://salsa.debian.org/js-team/node-hsluv/-/pipelines/309293

`SOURCE_DATE_EPOCH` is also used by nixos but is set to `1` in some cases. For example I found this: https://github.com/NixOS/nixpkgs/issues/112595

**Comment by boronine** [comment] 2021-11-01 13:40
Ok, I understand that, thanks. I'm just looking at your workaround code, so seems that your approach is not to download the tarball but to vendor the source files instead? Why not download the tarball and then override the timestamps there? Or is there another reason why you chose against the tarball?

I'm just curious to know because I'm a long-time user of Debian and would be happy to make my stuff more amenable to packaging. I realize Nix is probably at odds with Debian packaging since it's whole world of its own.

**Comment by josch** [comment] 2021-11-01 13:48
Maybe I'm misunderstanding. Are you asking why I'm downloading the tarball from the npm registry instead of using a tarball from github? If yes, then the answer is, that this git repository only contains tags named `_legacyjs*` which I didn't assume to be actual releases. Even if they were, the last tag is five years old. Also, the tag names do not seem to be the same as the versions on npm. Then even if I would use this git repository instead of the npm registry I would still need to vendor the tarball because it contains material that is certainly not DFSG-free, like the images in website/static/images or minified CSS.

**Comment by boronine** [comment] 2021-11-01 14:05
Actually I meant something else, but I appreciate knowing about the git tag issue and the non-DFSG issue, this is something I'm going to start thinking about.

Regarding the tarball, I was confused by the `missing-sources` directory and came to the conclusion that you decided to not download any tarball. After reviewing your code again I see you are downloading it using the `watch` file.

Now that I know that, I would ask a more correct question: why are you choosing to rebuild the Haxe sources? Does Debian policy prohibit using generated code like that contained in the hsluv NPM tarball?

**Comment by josch** [comment] 2021-11-01 14:45
Yes, no package in Debian must ship compiled code that was not produced from its original sources. You might argue that there is a difference between bytecode from an ELF executable and plain javascript that you can theoretically easily edit. The last time we had this discussion it was about minified javascript and it is project consensus that even code that is theoretically human readable but compiled from other sources must come with those sources.

**Comment by boronine** [comment] 2021-11-01 21:42
@josch I understand, thank you for taking the time to explain!

Upon consideration, I think your workaround may be the overall best solution. Closing this now.

**Closed by boronine** 2021-11-01 21:42 UTC
